import { buildQuadroInspectionArtifacts } from "../src/lib/quadro-template";

const payload = {
  numeroObra: "IRIS DO MAR",
  certNumber: "C-2061719",
  inspectionDate: "2026-10-06",
  nextInspectionDate: "2028-10-06",
  shipName: "IRIS DO MAR",
  brand: "DSB",
  raftModel: "LR07",
  raftCapacity: 25,
  raftSerial: "5086310502630",
  manufactureDate: "04/2023",
  cylinderSerial: "21W172085",
  cylinderGrossWeight: "",
  cylinderTare: "",
  cylinderCo2: "",
  cylinderN2: "",
  cylinderHydroTestDate: "2023-02",
  packType: "SOLAS B",
  pressureUnit: "mbar",
  tempInitial: 20,
  tempFinal: 20,
  baroInitial: 1010,
  baroFinal: 1010,
  wpStartTime: "09:00",
  wpEndTime: "10:00",
  wpUpperStart: 227,
  wpUpperEnd: 226,
  wpUpperCorrected: "",
  wpUpperDrop: "",
  wpUpperDropPercent: "",
  wpLowerStart: 22,
  wpLowerEnd: 227,
  wpLowerCorrected: "",
  wpLowerDrop: "",
  wpLowerDropPercent: "",
  napTestDone: "N/A",
  fsTestDone: "N/A",
  giTestDone: "N/A",
  dlTestDone: "N/A",
  checklist: {},
  substituicoes: [
    { descricao: "Abre-Latas", referencia: "CANONICO-21", quantidade: 2 },
    { descricao: "Ação Imediata", referencia: "CANONICO-16", quantidade: 1 },
    { descricao: "Ajudas Térmicas", referencia: "THER-BLANKET-TPA", quantidade: 3 },
    { descricao: "Âncora Flutuante com Linha", referencia: "DROGUE-ANCHOR", quantidade: 1 },
    { descricao: "Apito", referencia: "WHISTLE-SOLAS", quantidade: 1 },
    { descricao: "Comprimidos p/ Enjoo", referencia: "30202051", quantidade: 3 },
    { descricao: "Copo Graduado", referencia: "CANONICO-8", quantidade: 1 },
    { descricao: "Esponjas", referencia: "CANONICO-13", quantidade: 2 },
    { descricao: "Estojo de Pesca", referencia: "FISH-KIT", quantidade: 1 },
    { descricao: "Faca", referencia: "KNIFE-FLOATING", quantidade: 1 },
    { descricao: "Fachos de Mão", referencia: "20500035", quantidade: 3, validade: "2029-11-01" },
    { descricao: "Farmácia Solas", referencia: "12865009", quantidade: 1, validade: "2029-11-01" },
    { descricao: "Fole", referencia: "20402009", quantidade: 1 },
    { descricao: "Heliógrafo", referencia: "HELIOGRAPH", quantidade: 1 },
    { descricao: "Lanterna", referencia: "TORCH-WATERPROOF", quantidade: 1 },
    { descricao: "Manual de Sobrevivência", referencia: "MANUAL-SURVIVAL", quantidade: 1 },
    { descricao: "Pagaias", referencia: "CANONICO-15", quantidade: 2 },
    { descricao: "Foguetes Paraquedas", referencia: "20500023", quantidade: 2, validade: "2029-11-01" },
    { descricao: "Pilhas para Lanterna", referencia: "20903168", quantidade: 4 },
    { descricao: "Potes de Fumo", referencia: "20500002", quantidade: 1, validade: "2029-11-01" },
    { descricao: "Sacos para Enjoo", referencia: "BAG-SICKNESS", quantidade: 25 },
    { descricao: "Unidade de Libertação Hidrostática (HRU)", referencia: "20701002", quantidade: 1 },
    { descricao: "Jogo cintas contentor MK 10 Throwover - tamanho 7 (MK 10 Throwover 7 · 20P / 25P)", referencia: "D508", quantidade: 8 },
  ],
};

async function main() {
  await buildQuadroInspectionArtifacts(payload as never);
  console.log("OK");
}
main().catch((e) => { console.error("ERRO:", e); process.exit(1); });