import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getAccessContext } from "@/lib/access-control";
import { getIvaRate } from "@/lib/iva";
import { resolveActiveServiceStationId } from "@/lib/station-selection";
import { logAuditoria } from "@/lib/auditoria";
import type { Prisma } from "@prisma/client";
import {
  appendOrdemServicoLog,
  appendWorkflowTransition,
  autoGenerateDraftMaterialsForJangadas,
  generateNumeroOrdem,
  generateOSNumeroOrdem,
  mapOrderStatusToWorkflowStatus,
  normalizeUniquePositiveInts,
  normalizeOrdemPrioridade,
  normalizeOrdemStatus,
  normalizeOrdemTipo,
  parseOrdemServicoMeta,
  replaceOrdemServicoJangadas,
  resolveClienteIdForShipId,
  resolveOrderJangadasContext,
  resolveClienteIdForJangada,
  resolveWorkflowStatus,
  toOrdemServicoMetaJson,
  type OrdemServicoMeta,
  type OrdemWorkflowStatus,
} from "@/lib/ordens-servico";
import { parseFlexibleDate } from "@/lib/agenda-sync";
import { buildDatabaseErrorResponse } from "@/lib/database-errors";
import { getCanonicalNavioLocationLabel } from "@/lib/navios-page-helpers";

const ORDEM_INCLUDE = {
  jangada: {
    select: {
      id: true,
      serial: true,
      brand: true,
      model: true,
      owner: true,
      shipId: true,
      shipNameManual: true,
      numeroObra: true,
      dataInspecao: true,
      dataProxInspecao: true,
    },
  },
  ordemJangadas: {
    orderBy: [{ addedAt: "asc" }, { id: "asc" }],
    include: {
      jangada: {
        select: {
          id: true,
          serial: true,
          brand: true,
          model: true,
          owner: true,
          shipId: true,
          shipNameManual: true,
          numeroObra: true,
          dataInspecao: true,
          dataProxInspecao: true,
        },
      },
    },
  },
  cliente: {
    select: {
      id: true,
      nome: true,
      ilha: true,
      numeroCliente: true,
    },
  },
  tecnico: {
    select: {
      id: true,
      nome: true,
      email: true,
      ativo: true,
    },
  },
  inspecao: {
    select: {
      id: true,
      certificadoNumero: true,
      dataInspecao: true,
      dataProxInspecao: true,
      status: true,
      testeWP: true,
      testeNAP: true,
      testeFS: true,
      testeGI: true,
      testeDL: true,
    },
  },
  serviceStationQueues: {
    orderBy: [{ updatedAt: "desc" }, { id: "desc" }],
    take: 1,
    select: {
      id: true,
      status: true,
      dataChegada: true,
      dataPrevistaEntrega: true,
    },
  },
  serviceStation: {
    select: {
      id: true,
      codigo: true,
      nome: true,
    },
  },
} satisfies Prisma.OrdemServicoInclude;

type OrdemServicoRow = Prisma.OrdemServicoGetPayload<{ include: typeof ORDEM_INCLUDE }>;

function normalizeListNumber(value: unknown) {
  if (!Array.isArray(value)) return [] as number[];
  return normalizeUniquePositiveInts(value);
}

function applyServiceStationScope(where: Record<string, unknown>, req: NextRequest, access: Awaited<ReturnType<typeof getAccessContext>>) {
  if (!access) return;

  const activeStationId = resolveActiveServiceStationId(req, access);
  if (activeStationId) {
    where.serviceStationId = activeStationId;
    return;
  }

  if (!access.isAdmin) {
    if (access.allowedStationIds.length > 0) {
      where.serviceStationId = { in: access.allowedStationIds };
    } else if (access.stationId) {
      where.serviceStationId = access.stationId;
    }
  }
}

async function resolveJangadaIds(body: Record<string, unknown>) {
  const explicitIds = normalizeListNumber(body.jangadaIds);
  if (explicitIds.length > 0) return explicitIds;

  const singleId = Number(body.jangadaId || body.raftId);
  if (Number.isFinite(singleId) && singleId > 0) return [singleId];

  const serial = String(body.serial || "").trim();
  if (!serial) return [];

  const raft = await prisma.jangada.findFirst({
    where: { serial: { equals: serial } },
    select: { id: true },
  });

  return raft?.id ? [raft.id] : [];
}

function parseOptionalDate(value: unknown) {
  const parsed = parseFlexibleDate(String(value || "").trim());
  return parsed || null;
}

function parseOptionalPositiveInt(value: unknown) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return null;
  return Math.floor(parsed);
}

async function resolveTecnicoPayload(tecnicoIdValue: unknown, tecnicoResponsavelValue: unknown) {
  const tecnicoId = parseOptionalPositiveInt(tecnicoIdValue);
  if (!tecnicoId) {
    return {
      tecnicoId: null as number | null,
      tecnicoResponsavel: String(tecnicoResponsavelValue || "").trim() || null,
    };
  }

  const tecnico = await prisma.tecnico.findUnique({
    where: { id: tecnicoId },
    select: { id: true, nome: true, ativo: true },
  });

  if (!tecnico || !tecnico.ativo) {
    return null;
  }

  return {
    tecnicoId: tecnico.id,
    tecnicoResponsavel: tecnico.nome,
  };
}

function buildDefaultChecklistRows(tipo: string) {
  const isInspection = String(tipo || "").toLowerCase() === "inspecao";
  return [
    { phase: "pre", label: "Confirmar dados da OT e ativo" },
    { phase: "pre", label: "Validar condições de segurança" },
    { phase: "intervencao", label: isInspection ? "Executar checklist de inspeção da jangada" : "Executar procedimento técnico principal" },
    { phase: "intervencao", label: "Registar materiais/consumos" },
    { phase: "validacao", label: "Validar resultado final" },
    { phase: "validacao", label: "Confirmar documentação e evidências" },
  ];
}

async function buildLatestInspectionSummaryForOrders(serializedOrders: ReturnType<typeof serializeOrder>[]) {
  const allJangadas = serializedOrders.flatMap((order) => Array.isArray(order?.jangadas) ? order.jangadas : []);
  const jangadaIds = Array.from(new Set(
    allJangadas
      .map((jangada) => Number(jangada?.id))
      .filter((id) => Number.isFinite(id) && id > 0)
  ));

  if (jangadaIds.length === 0) {
    return serializedOrders;
  }

  const inspections = await prisma.inspecao.findMany({
    where: {
      jangadaId: { in: jangadaIds },
    },
    orderBy: [{ dataInspecao: "desc" }, { updatedAt: "desc" }, { id: "desc" }],
    select: {
      id: true,
      jangadaId: true,
      certificadoNumero: true,
      dataInspecao: true,
      dataProxInspecao: true,
      status: true,
      testeWP: true,
      testeNAP: true,
      testeFS: true,
      testeGI: true,
      testeDL: true,
      artigos: {
        select: {
          id: true,
          name: true,
          referencia: true,
          quantidade: true,
        },
      },
    },
  });

  const latestInspectionByJangada = new Map<number, (typeof inspections)[number]>();
  for (const inspection of inspections) {
    const jangadaId = Number(inspection.jangadaId);
    if (!Number.isFinite(jangadaId) || jangadaId <= 0 || latestInspectionByJangada.has(jangadaId)) {
      continue;
    }
    latestInspectionByJangada.set(jangadaId, inspection);
  }

  return serializedOrders.map((order) => {
    const jangadas = Array.isArray(order?.jangadas) ? order.jangadas : [];
    const latestInspectionContext = jangadas.map((jangada) => {
      const inspection = latestInspectionByJangada.get(Number(jangada?.id));
      const hasReprovado = (value: string | null) => {
        const v = String(value || "").trim().toUpperCase();
        return v === "REPROVOU" || v === "REPROVADO";
      };
      const testesReprovados = inspection ? [
        hasReprovado(inspection.testeWP) ? "WP" : null,
        hasReprovado(inspection.testeNAP) ? "NAP" : null,
        hasReprovado(inspection.testeFS) ? "FS" : null,
        hasReprovado(inspection.testeGI) ? "GI" : null,
        hasReprovado(inspection.testeDL) ? "DL" : null,
      ].filter(Boolean) : [];

      return {
        jangadaId: Number(jangada?.id),
        serial: jangada?.serial || "",
        brand: jangada?.brand || null,
        model: jangada?.model || null,
        certificadoNumero: inspection?.certificadoNumero || null,
        dataInspecao: inspection?.dataInspecao || null,
        dataProxInspecao: inspection?.dataProxInspecao || null,
        status: inspection?.status || null,
        testes: {
          WP: inspection?.testeWP || null,
          NAP: inspection?.testeNAP || null,
          FS: inspection?.testeFS || null,
          GI: inspection?.testeGI || null,
          DL: inspection?.testeDL || null,
        },
        testesReprovados,
        artigosSubstituidosCount: Array.isArray(inspection?.artigos) ? inspection.artigos.length : 0,
        artigos: Array.isArray(inspection?.artigos)
          ? inspection.artigos.map((a) => ({ id: a.id, name: a.name, referencia: a.referencia, quantidade: a.quantidade }))
          : [],
      };
    });

    const historyCount = latestInspectionContext.filter((item) => item.dataInspecao).length;
    const replacementCount = latestInspectionContext.reduce((acc, item) => acc + Number(item.artigosSubstituidosCount || 0), 0);
    const totalTestesReprovados = latestInspectionContext.reduce((acc, item) => acc + (item.testesReprovados?.length || 0), 0);

    return {
      ...order,
      latestInspectionContext,
      latestInspectionSummary: {
        historyCount,
        replacementCount,
        totalTestesReprovados,
        latestDate: latestInspectionContext
          .map((item) => String(item.dataInspecao || "").trim())
          .filter(Boolean)
          .sort((a, b) => b.localeCompare(a))[0] || null,
      },
    };
  });
}

function serializeOrder(row: OrdemServicoRow) {
  const meta = parseOrdemServicoMeta(row.metadados);
  const queue = Array.isArray(row.serviceStationQueues) ? row.serviceStationQueues[0] : null;
  const jangadas = (() => {
    const linked = Array.isArray(row.ordemJangadas)
      ? row.ordemJangadas.map((link) => link?.jangada).filter(Boolean)
      : [];
    const combined = [...linked, row.jangada].filter(Boolean);
    const seen = new Set<number>();
    return combined.filter((jangada): jangada is NonNullable<typeof jangada> => {
      const id = Number(jangada?.id);
      if (!Number.isFinite(id) || seen.has(id)) return false;
      seen.add(id);
      return true;
    });
  })();
  const primaryJangada = jangadas[0] || row.jangada || null;
  const workflowStatus = resolveWorkflowStatus({ meta, orderStatus: row.status });

  return {
    id: row.id,
    numeroOrdem: row.numeroOrdem,
    grupoNumeroOrdem: meta.grupoNumeroOrdem || null,
    tipo: row.tipo,
    prioridade: row.prioridade,
    status: row.status,
    workflowStatus,
    descricao: row.descricao || "",
    tecnicoId: row.tecnicoId ?? row.tecnico?.id ?? null,
    tecnicoResponsavel: row.tecnicoResponsavel || "",
    tecnico: row.tecnico ? {
      id: row.tecnico.id,
      nome: row.tecnico.nome,
      email: row.tecnico.email,
      ativo: row.tecnico.ativo,
    } : null,
    slaHoras: row.slaHoras ?? null,
    dataPlaneadaInicio: row.dataPlaneadaInicio?.toISOString() || null,
    dataPlaneadaFim: row.dataPlaneadaFim?.toISOString() || null,
    dataAbertura: row.dataAbertura?.toISOString() || null,
    dataPrevista: row.dataPrevista?.toISOString() || null,
    dataInicio: row.dataInicio?.toISOString() || null,
    dataConclusao: row.dataConclusao?.toISOString() || null,
    durationMinutes: row.durationMinutes || 0,
    orcamentoStatus: row.orcamentoStatus || "Rascunho",
    isPesca: row.isPesca || false,
    isIsentoIva: row.isIsentoIva || false,
    valorPecas: row.valorPecas || 0,
    valorMaoObra: row.valorMaoObra || 0,
    valorDesconto: row.valorDesconto || 0,
    valorTotal: row.valorTotal || 0,
    metadados: meta,
    jangadaId: primaryJangada?.id || row.jangadaId,
    shipId: primaryJangada?.shipId ?? row.shipId ?? meta.shipId ?? null,
    clienteId: row.clienteId || null,
    inspecaoId: row.inspecaoId || null,
    jangada: primaryJangada ? {
      id: primaryJangada.id,
      serial: primaryJangada.serial,
      brand: primaryJangada.brand,
      model: primaryJangada.model,
      owner: primaryJangada.owner,
      shipId: primaryJangada.shipId,
      shipNameManual: primaryJangada.shipNameManual,
      numeroObra: primaryJangada.numeroObra,
      dataInspecao: primaryJangada.dataInspecao,
      dataProxInspecao: primaryJangada.dataProxInspecao,
    } : null,
    jangadas: jangadas.map((jangada) => ({
      id: jangada.id,
      serial: jangada.serial,
      brand: jangada.brand,
      model: jangada.model,
      owner: jangada.owner,
      shipId: jangada.shipId,
      shipNameManual: jangada.shipNameManual,
      numeroObra: jangada.numeroObra,
      dataInspecao: jangada.dataInspecao,
      dataProxInspecao: jangada.dataProxInspecao,
    })),
    cliente: row.cliente ? {
      id: row.cliente.id,
      nome: row.cliente.nome,
      ilha: (getCanonicalNavioLocationLabel(row.cliente.ilha) || row.cliente.ilha) || null,
      numeroCliente: row.cliente.numeroCliente,
    } : null,
    inspecao: row.inspecao ? {
      id: row.inspecao.id,
      certificadoNumero: row.inspecao.certificadoNumero,
      dataInspecao: row.inspecao.dataInspecao,
      dataProxInspecao: row.inspecao.dataProxInspecao,
      status: row.inspecao.status,
      testes: {
        WP: row.inspecao.testeWP || null,
        NAP: row.inspecao.testeNAP || null,
        FS: row.inspecao.testeFS || null,
        GI: row.inspecao.testeGI || null,
        DL: row.inspecao.testeDL || null,
      },
    } : null,
    serviceStation: queue ? {
      id: row.serviceStation?.id ?? null,
      codigo: row.serviceStation?.codigo ?? null,
      nome: row.serviceStation?.nome ?? null,
      queueId: queue.id,
      status: queue.status,
      dataChegada: queue.dataChegada?.toISOString() || null,
      dataPrevistaEntrega: queue.dataPrevistaEntrega?.toISOString() || null,
    } : (row.serviceStation ? {
      id: row.serviceStation.id,
      codigo: row.serviceStation.codigo,
      nome: row.serviceStation.nome,
      queueId: null,
      status: null,
      dataChegada: null,
      dataPrevistaEntrega: null,
    } : null),
    createdAt: row.createdAt?.toISOString() || null,
    updatedAt: row.updatedAt?.toISOString() || null,
  };
}

async function fetchOrders(where?: Record<string, unknown>) {
  const rows = await prisma.ordemServico.findMany({
    where,
    orderBy: [{ updatedAt: "desc" }, { id: "desc" }],
    include: ORDEM_INCLUDE,
  });

  const serialized = rows.map(serializeOrder);
  return buildLatestInspectionSummaryForOrders(serialized);
}

function parsePagination(searchParams: URLSearchParams) {
  const page = Math.max(0, Number(searchParams.get("page") || 0));
  const requestedPageSize = Number(searchParams.get("pageSize") || 20);
  const pageSize = Math.min(100, Math.max(1, Number.isFinite(requestedPageSize) ? requestedPageSize : 20));
  const sort = String(searchParams.get("sort") || "").trim();
  const sortDir = String(searchParams.get("sortDir") || "desc").trim().toLowerCase() as "asc" | "desc";
  const q = String(searchParams.get("q") || "").trim();
  return { page, pageSize, sort, sortDir, q, paginated: searchParams.has("page") || searchParams.has("pageSize") };
}

function buildSearchWhere(q: string) {
  // SQLite provider does not support `mode: "insensitive"`; LIKE on TEXT is case-insensitive by default.
  return {
    OR: [
      { numeroOrdem: { contains: q } },
      { grupoNumeroOrdem: { contains: q } },
      { descricao: { contains: q } },
      { tecnicoResponsavel: { contains: q } },
      { cliente: { nome: { contains: q } } },
      { jangada: { serial: { contains: q } } },
      { jangada: { brand: { contains: q } } },
      { jangada: { model: { contains: q } } },
      { ordemJangadas: { some: { jangada: { serial: { contains: q } } } } },
      { ordemJangadas: { some: { jangada: { brand: { contains: q } } } } },
      { ordemJangadas: { some: { jangada: { model: { contains: q } } } } },
    ],
  };
}

function buildOrderBy(sort: string, sortDir: "asc" | "desc"): Prisma.OrdemServicoOrderByWithRelationInput {
  const dir = sortDir === "asc" ? "asc" : "desc";
  const allowedScalar = new Set([
    "id",
    "numeroOrdem",
    "status",
    "prioridade",
    "tipo",
    "dataAbertura",
    "dataPlaneadaInicio",
    "dataPlaneadaFim",
    "dataPrevista",
    "dataConclusao",
    "updatedAt",
    "createdAt",
    "valorTotal",
    "orcamentoStatus",
  ]);
  if (allowedScalar.has(sort)) {
    return { [sort]: dir } as unknown as Prisma.OrdemServicoOrderByWithRelationInput;
  }
  if (sort === "cliente") return { cliente: { nome: dir } };
  if (sort === "tecnico") return { tecnico: { nome: dir } };
  if (sort === "jangada") return { jangada: { serial: dir } };
  return { updatedAt: dir };
}

async function fetchOrdersPaginated(
  where: Record<string, unknown>,
  page: number,
  pageSize: number,
  sort: string,
  sortDir: "asc" | "desc"
) {
  const orderBy = buildOrderBy(sort, sortDir);
  const [total, rows] = await Promise.all([
    prisma.ordemServico.count({ where }),
    prisma.ordemServico.findMany({
      where,
      orderBy,
      skip: page * pageSize,
      take: pageSize,
      include: ORDEM_INCLUDE,
    }),
  ]);

  const serialized = rows.map(serializeOrder);
  const orders = await buildLatestInspectionSummaryForOrders(serialized);
  return { total, orders, page, pageSize, totalPages: Math.ceil(total / pageSize) };
}

export async function GET(req: NextRequest) {
  try {
    const access = await getAccessContext();
    console.log("[API /ordens-servico] getAccessContext result:", access ? { userId: access.userId, email: access.email, role: access.role, isAdmin: access.isAdmin } : "NULL");
    if (!access) {
      console.log("[API /ordens-servico] Cookies:", req.cookies.getAll().map(c => c.name));
      return NextResponse.json({ error: "Sessão obrigatória." }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const jangadaId = Number(searchParams.get("jangadaId"));
    const clienteId = Number(searchParams.get("clienteId"));
    const status = searchParams.get("status");
    const prioridade = searchParams.get("prioridade");
    const tecnico = String(searchParams.get("tecnicoResponsavel") || "").trim();
    const tecnicoId = parseOptionalPositiveInt(searchParams.get("tecnicoId"));
    const atraso = searchParams.get("atraso") === "1";
    const includeClosed = searchParams.get("includeClosed") === "1";
    const planeadoInicioDe = parseOptionalDate(searchParams.get("planeadoInicioDe"));
    const planeadoInicioAte = parseOptionalDate(searchParams.get("planeadoInicioAte"));
    const planeadoFimDe = parseOptionalDate(searchParams.get("planeadoFimDe"));
    const planeadoFimAte = parseOptionalDate(searchParams.get("planeadoFimAte"));
    const aberturaDe = parseOptionalDate(searchParams.get("aberturaDe"));
    const aberturaAte = parseOptionalDate(searchParams.get("aberturaAte"));
    const conclusaoDe = parseOptionalDate(searchParams.get("conclusaoDe"));
    const conclusaoAte = parseOptionalDate(searchParams.get("conclusaoAte"));
    const { page, pageSize, sort, sortDir, q, paginated } = parsePagination(searchParams);

    const where: Record<string, unknown> = {};
    applyServiceStationScope(where, req, access);
    if (Number.isFinite(jangadaId) && jangadaId > 0) {
      where.OR = [
        { jangadaId },
        { ordemJangadas: { some: { jangadaId } } },
      ];
    }
    if (Number.isFinite(clienteId) && clienteId > 0) where.clienteId = clienteId;
    if (status) where.status = normalizeOrdemStatus(status);
    const orcamentoStatus = searchParams.get("orcamentoStatus");
    if (orcamentoStatus) where.orcamentoStatus = orcamentoStatus;
    if (prioridade) where.prioridade = normalizeOrdemPrioridade(prioridade);
    if (tecnicoId) {
      where.tecnicoId = tecnicoId;
    }
    if (tecnico) where.tecnicoResponsavel = { contains: tecnico };
    if (!includeClosed && !status) where.status = { notIn: ["concluida", "cancelada"] };

    if (planeadoInicioDe || planeadoInicioAte) {
      where.dataPlaneadaInicio = {
        ...(planeadoInicioDe ? { gte: planeadoInicioDe } : {}),
        ...(planeadoInicioAte ? { lte: planeadoInicioAte } : {}),
      };
    }

    if (planeadoFimDe || planeadoFimAte) {
      where.dataPlaneadaFim = {
        ...(planeadoFimDe ? { gte: planeadoFimDe } : {}),
        ...(planeadoFimAte ? { lte: planeadoFimAte } : {}),
      };
    }

    if (aberturaDe || aberturaAte) {
      where.dataAbertura = {
        ...(aberturaDe ? { gte: aberturaDe } : {}),
        ...(aberturaAte ? { lte: aberturaAte } : {}),
      };
    }

    if (conclusaoDe || conclusaoAte) {
      where.dataConclusao = {
        ...(conclusaoDe ? { gte: conclusaoDe } : {}),
        ...(conclusaoAte ? { lte: conclusaoAte } : {}),
      };
    }

    if (atraso) {
      const andClauses = Array.isArray(where.AND) ? where.AND : [];
      andClauses.push({ dataPlaneadaFim: { lt: new Date() } });
      andClauses.push({ status: { notIn: ["concluida", "cancelada"] } });
      where.AND = andClauses;
    }

    if (q) {
      const searchWhere = buildSearchWhere(q);
      if (Array.isArray(where.AND)) {
        where.AND.push(searchWhere);
      } else if (where.AND) {
        where.AND = [where.AND, searchWhere];
      } else {
        where.AND = searchWhere;
      }
    }

    if (paginated) {
      const result = await fetchOrdersPaginated(where, page, pageSize, sort, sortDir);
      return NextResponse.json(result);
    }

    const rows = await fetchOrders(where);
    return NextResponse.json(rows);
  } catch (error) {
    console.error("[GET /api/ordens-servico]", error);
    return buildDatabaseErrorResponse(error, "Erro ao listar ordens de serviço.");
  }
}

export async function POST(req: NextRequest) {
  try {
    const access = await getAccessContext();
    if (!access) {
      return NextResponse.json({ error: "Sessão obrigatória." }, { status: 401 });
    }

    const body = (await req.json()) as Record<string, unknown>;
    const jangadaIds = await resolveJangadaIds(body);
    if (jangadaIds.length === 0) {
      return NextResponse.json({ error: "jangadaId/jangadaIds inválidos." }, { status: 400 });
    }

    let jangadaContext = await resolveOrderJangadasContext(jangadaIds);
    const explicitShipId = Number(body.shipId);
    if (Number.isFinite(explicitShipId) && explicitShipId > 0 && explicitShipId !== jangadaContext.shipId) {
      // Modo cascata: o navio foi escolhido explicitamente mas as jangadas
      // selecionadas têm outro shipId (ou ainda não têm). Em vez de rejeitar,
      // associar as jangadas ao navio indicado para manter a OT coerente.
      await prisma.jangada.updateMany({
        where: { id: { in: jangadaIds } },
        data: { shipId: explicitShipId },
      });
      const refreshedContext = await resolveOrderJangadasContext(jangadaIds);
      if (refreshedContext.shipId && explicitShipId !== refreshedContext.shipId) {
        return NextResponse.json({ error: "As jangadas selecionadas não pertencem ao navio indicado." }, { status: 400 });
      }
      jangadaContext = refreshedContext;
    }

    const status = normalizeOrdemStatus(body.status);
    const dataPlaneadaInicio = parseOptionalDate(body.dataPlaneadaInicio);
    const dataPlaneadaFim = parseOptionalDate(body.dataPlaneadaFim);
    const dataPrevista = parseOptionalDate(body.dataPrevista);
    const dataInicio = parseOptionalDate(body.dataInicio);
    const dataConclusao = parseOptionalDate(body.dataConclusao);
    const explicitBaseNumber = String(body.numeroBase || "").trim();
    const referenceDate = dataPlaneadaInicio
      || dataPrevista
      || dataInicio
      || dataConclusao
      || new Date();

    const numeroOrdem = status === "em_progresso"
      ? await generateNumeroOrdem(referenceDate)
      : await generateOSNumeroOrdem(referenceDate);
    const groupNumber = String(body.grupoNumeroOrdem || explicitBaseNumber || numeroOrdem).trim() || numeroOrdem;
    const tipo = normalizeOrdemTipo(body.tipo);
    const prioridade = normalizeOrdemPrioridade(body.prioridade);
    const workflowStatus = resolveWorkflowStatus({
      meta: { workflowStatus: body.workflowStatus as OrdemWorkflowStatus | undefined },
      orderStatus: status,
    }) || mapOrderStatusToWorkflowStatus(status) || "orcamento_em_preparacao";
    const descricao = String(body.descricao || "").trim() || null;
    const tecnicoPayload = await resolveTecnicoPayload(body.tecnicoId, body.tecnicoResponsavel);
    if (body.tecnicoId && !tecnicoPayload) {
      return NextResponse.json({ error: "Técnico inválido ou inativo." }, { status: 400 });
    }
    const tecnicoResponsavel = tecnicoPayload?.tecnicoResponsavel ?? null;
    const tecnicoIdResolved = tecnicoPayload?.tecnicoId ?? null;
    const slaHoras = parseOptionalPositiveInt(body.slaHoras);
    const durationMinutes = Math.max(0, Number(body.durationMinutes || 210)) || 210;
    const providedMeta = body.metadados && typeof body.metadados === "object" ? body.metadados as Record<string, unknown> : {};

    const clienteId = Number(body.clienteId);
    const resolvedClienteId = Number.isFinite(clienteId) && clienteId > 0
      ? clienteId
      : (jangadaContext.shipId ? await resolveClienteIdForShipId(jangadaContext.shipId) : await resolveClienteIdForJangada(jangadaContext.primaryJangadaId || 0));
    let draftMaterials: NonNullable<OrdemServicoMeta["materials"]> = [];
    let computedValorPecas = 0;

    if (Array.isArray(providedMeta.materials) && providedMeta.materials.length > 0) {
      draftMaterials = providedMeta.materials as NonNullable<OrdemServicoMeta["materials"]>;
      computedValorPecas = Number(body.valorPecas || 0);
    } else if (jangadaIds && jangadaIds.length > 0) {
      const generated = await autoGenerateDraftMaterialsForJangadas(jangadaIds, tipo);
      draftMaterials = generated.materials;
      computedValorPecas = generated.valorPecas;
    }

    const valorMaoObra = Number(body.valorMaoObra || 0);
    const valorDesconto = Number(body.valorDesconto || 0);
    const isIsentoIva = Boolean(body.isIsentoIva);
    const valorPecas = Number(body.valorPecas || computedValorPecas);
    const subtotal = Math.max(0, valorPecas + valorMaoObra - valorDesconto);
    const iva = isIsentoIva ? 0 : subtotal * getIvaRate();
    const valorTotal = Number(body.valorTotal || subtotal + iva);
    const baseMeta = {
      grupoNumeroOrdem: groupNumber,
      origem: String(body.origem || "manual").trim() || "manual",
      shipId: jangadaContext.shipId ?? (Number.isFinite(explicitShipId) ? explicitShipId : undefined),
      shipName: String(body.shipName || "").trim() || jangadaContext.shipName || undefined,
      materials: draftMaterials,
      linhas: Array.isArray(providedMeta.linhas) ? providedMeta.linhas : undefined,
      totais: providedMeta.totais && typeof providedMeta.totais === "object" ? providedMeta.totais as Record<string, number> : undefined,
      observacao: String(providedMeta.observacao || "").trim() || undefined,
    };

    const metaWithLog = appendOrdemServicoLog(appendWorkflowTransition(baseMeta, workflowStatus, {
      origin: "order",
      message: `Workflow inicial definido para ${workflowStatus}.`,
      user: tecnicoResponsavel || "sistema",
    }), {
      type: "CREATE",
      message: `OT criada (${numeroOrdem}) com ${jangadaIds.length} jangada(s).`,
      user: "sistema",
    });

    const created = await prisma.$transaction(async (tx) => {
      const order = await tx.ordemServico.create({
        data: {
          numeroOrdem,
          serviceStationId: jangadaContext.serviceStationId,
          jangadaId: jangadaContext.primaryJangadaId!,
          shipId: jangadaContext.shipId,
          clienteId: resolvedClienteId,
          tecnicoId: tecnicoIdResolved,
          inspecaoId: Number.isFinite(Number(body.inspecaoId)) ? Number(body.inspecaoId) : null,
          tipo,
          prioridade,
          status,
          descricao,
          tecnicoResponsavel,
          slaHoras,
          dataPlaneadaInicio,
          dataPlaneadaFim,
          dataPrevista,
          dataInicio,
          dataConclusao,
          durationMinutes,
          valorPecas,
          valorMaoObra,
          valorDesconto,
          valorTotal,
          isIsentoIva,
          metadados: toOrdemServicoMetaJson(metaWithLog),
        },
      });

      await replaceOrdemServicoJangadas(tx as typeof prisma, order.id, jangadaIds);

      await tx.ordemServicoChecklistItem.createMany({
        data: buildDefaultChecklistRows(tipo).map((item) => ({
          ordemServicoId: order.id,
          phase: item.phase,
          label: item.label,
          done: false,
        })),
      });

      await tx.ordemServicoLog.create({
        data: {
          ordemServicoId: order.id,
          type: "CREATE",
          message: `OT criada (${numeroOrdem}) com ${jangadaIds.length} jangada(s).`,
          user: "sistema",
        },
      });

      await tx.jangada.updateMany({
        where: { id: { in: jangadaIds } },
        data: { numeroObra: groupNumber },
      });

      return order;
    });

    await logAuditoria({
      tabela: "OrdemServico",
      tipoOperacao: "CREATE",
      idRegisto: created.id,
      descricao: `Criação de OT ${numeroOrdem} com ${jangadaIds.length} jangada(s)` ,
      dadosDepois: created,
    });

    const rows = await fetchOrders({ id: created.id });
    return NextResponse.json(rows, { status: 201 });
  } catch (error) {
    console.error("[POST /api/ordens-servico]", error);
    const detail = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: "Erro ao criar ordem de serviço.", detail }, { status: 500 });
  }
}
